### PR TITLE
Shared pointers

### PR DESCRIPTION
**Pull request by kylelin47**

### CODE REVIEW

**Comment by kylelin47** [comment]
I changed all pointers to shared_ptr to handle deletion of new objects but this is not compatible with the parser as is. All that needs to change is that everywhere it pushes back a "new" object in the parser it needs to push back a shared_ptr to that new object.

**Comment by alexs10** [comment]
I would undo this. Every thing is in a vector, call vector.clear() in the destructor, which calls the destructor for all the elements. Then have every elements destuctor say something like this->delete. That makes the most sense

**Comment by kylelin47** [comment]
vector.clear() when applied to a vector of pointers will just destruct the pointers, the objects they're pointing to will still exist in memory.

could have destructor for Sum/Mult iterate through their vectors and call delete on every element that the vector points to and every other number type's destructor will delete their relevant things (ex: radical will delete base and value AbstractNumber*) and it should work

but shared_ptr works too...

**Comment by kylelin47** [comment]
Don't worry about shared pointers while writing your own parts. It's easy enough to add them in if we end up using them and taking them out if we don't.

**Pull request merged**
